{
 "title": "My Grafana Test Board",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(network_latency_seconds_sum[1m]) / rate(network_latency_seconds_count[1m])) by (provider)",
     "legendFormat": "{{provider}}"
    },
    {
     "expr": "min(rate(network_latency_seconds_sum[1m]) / rate(network_latency_seconds_count[1m])) by (provider)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(network_latency_seconds_sum[1m]) / rate(network_latency_seconds_count[1m])) by (provider)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(network_throughput_bytes_total{direction=\"download\"}[1m])) by (provider)",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(rate(network_throughput_bytes_total{direction=\"download\"}[1m])) by (provider)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(network_throughput_bytes_total{direction=\"download\"}[1m])) by (provider)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(network_throughput_bytes_total{direction=\"upload\"}[1m])) by (provider)",
     "legendFormat": "{{provider}}"
    },
    {
     "expr": "min(rate(network_throughput_bytes_total{direction=\"upload\"}[1m])) by (provider)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rate(network_throughput_bytes_total{direction=\"upload\"}[1m])) by (provider)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total[1m])",
     "legendFormat": "{{provider}}"
    },
    {
     "expr": "rate(node_network_transmit_errs_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_receive_drop_total[1m]) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_tcp_connections_established[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}